# Data Sources

## Raw data

### Indices of Multiple Deprivation (IMD) (2019) Data

(Ministry of Housing, Communities, and Local Government)\
[https://www.gov.uk/government/statistics/english-indices-of-deprivation-2019](https://www.gov.uk/government/statistics/english-indices-of-deprivation-2019){target="_blank"}

## Publicly Accessible Analysis & Dashboards

### PowerBI dashboard of NHS Acute Trust Catchment Populations

(Office for Health Improvement and Disparities)\
[NHS Acute (Hospital) Trust Catchment Populations](https://app.powerbi.com/view?r=eyJrIjoiODZmNGQ0YzItZDAwZi00MzFiLWE4NzAtMzVmNTUwMThmMTVlIiwidCI6ImVlNGUxNDk5LTRhMzUtNGIyZS1hZDQ3LTVmM2NmOWRlODY2NiIsImMiOjh9){target="_blank"}

## Dashboards requiring authentication

### Health Inequalities Improvement Programme Dashboard (getting access)

(NHS England)\
[Health Inequalities Improvement Programme Dashboard (getting access)](https://future.nhs.uk/connect.ti/InequalitiesImprovement/view?objectID=42240816){target="_blank"}

### SHAPE Tool

(Department of Health and Social Care) [SHAPE](https://app.shapeatlas.net/place){target="_blank"}

## Code lists

Mental Health from Health Foundation's [Network Data Labs](https://github.com/HFAnalyticsLab/Mental-health-code-lists)

Includes code lists for

-   Depression
-   Anxiety
-   Self harm
-   Eating disorders
-   Alcohol misuse
-   Substance misuse
-   Severe mental illness

A wide range of code lists from [OpenCodelists](https://www.opencodelists.org/).

### Frailty

[Frailty Score Calculation](https://github.com/Simon-W-M/frailty_score_calculation)

## UK addresses

Useful blog detailing some incorrect assumptions on UK addresses and postcodes:
<https://www.mjt.me.uk/posts/falsehoods-programmers-believe-about-addresses/>