---
title: "Inclusion Health"
---

> Inclusion health is an umbrella term used to describe people who are socially excluded, who typically experience multiple interacting risk factors for poor health, such as stigma, discrimination, poverty, violence, and complex trauma.

[NHS England National Framework for NHS action on inclusion health](https://www.england.nhs.uk/long-read/a-national-framework-for-nhs-action-on-inclusion-health/)

Finding these groups in data can be particularly difficult.
Groups include:

- People who experience homelessness
- People with drug and alcohol dependence
- Vulnerable migrants and refugees
- Gypsy, Roma, and Traveller communities
- People in contact with the justice system
- Victims of modern slavery
- Sex workers
- Other marginalised groups

## Postcodes 

### England

Homelessness and no fixed abode have implications for commissioning under usual place of residence but also for health inequality analysis.
The guidance for [commissioner assignment](https://www.england.nhs.uk/long-read/commissioner-assignment-method-flow-chart-2024-25-accompanying-guidance-and-reference-tables/).

Some data may have the postcode from the main site of the provider delivering care instead of an agreed postcode such as `ZZ99 3VZ` for `No Fixed Abode` or `Address not known` should be `ZZ99 3WZ`.

Note that some `ZZ` postcodes will related to unspecified UK country codes:

- `England UK – not specified` - `Z99 3CZ`  
- `Wales` - `ZZ99 3GZ`  
- `Scotland` - `ZZ99 1WZ`  
- `Northern Ireland` - `ZZ99 2WZ`

The [Data Dictionary](https://v2.datadictionary.nhs.uk/data_dictionary/data_field_notes/p/postcode_of_usual_address_de.asp@shownav=0.html) for Postcode of Usual Address that refers to these postcodes is now archived.

### Scotland

According to [NHS Tayside](https://www.nhstaysidecdn.scot.nhs.uk/NHSTaysideWeb/idcplg?IdcService=GET_SECURE_FILE&dDocName=PROD_315642&Rendition=web&RevisionSelectionMethod=LatestReleased&noSaveAs=1#) if a person has no fixed address it is classified as `NF1 1AB`.

### Wales

The [Data dictionary](https://www.datadictionary.wales.nhs.uk/index.html#!WordDocuments/postcode.htm) is distinct for NHS Wales.

## Public Health / Office for Health Improvement and Disparities

South East Clinical Delivery and Networks[webinars 2023-2024](https://www.southeastclinicalnetworks.nhs.uk/homelessness-and-rough-sleeping-webinars-2023-24/) and datapacks.

[Spotlight tool](https://analytics.phe.gov.uk/apps/spotlight/) collates and presents key statistics related to the public health outcomes of Inclusion health groups across the following themes: access to and utilisation of health care; preventative care; health outcomes; and wider determinants of health.

## Networks

FutureNHS [Population Health Academy](https://future.nhs.uk/populationhealth) - requires log on, anyone may join.

> This Academy is for anyone using data and insights to improve health and care, drive collaboration and prioritise prevention through systems, place-based partnerships and integrated neighbourhood teams. Find the most up to date resources, discuss challenges and share best practice. 